// City -> county lookup for the states this site covers.
//
// Loaded before script.js on the pages with a location picker. Keeping it out of
// script.js keeps ~500 lines of pure data away from the application logic.
//
// The city list is the same set of incorporated places the site already used;
// the county for each was added alongside. County lists are derived from the
// values here, so there is one source of truth.
globalThis.LOCATION_DATA = {
  ID: {
    label: 'Idaho',
    cities: {
      'Aberdeen': 'Bingham',
      'Acequia': 'Minidoka',
      'Albion': 'Cassia',
      'American Falls': 'Power',
      'Ammon': 'Bonneville',
      'Arco': 'Butte',
      'Arimo': 'Bannock',
      'Ashton': 'Fremont',
      'Athol': 'Kootenai',
      'Bancroft': 'Caribou',
      'Basalt': 'Bingham',
      'Bellevue': 'Blaine',
      'Blackfoot': 'Bingham',
      'Bliss': 'Gooding',
      'Bloomington': 'Bear Lake',
      'Boise': 'Ada',
      'Bonners Ferry': 'Boundary',
      'Bovill': 'Latah',
      'Buhl': 'Twin Falls',
      'Burley': 'Cassia',
      'Butte City': 'Butte',
      'Caldwell': 'Canyon',
      'Cambridge': 'Washington',
      'Carey': 'Blaine',
      'Cascade': 'Valley',
      'Castleford': 'Twin Falls',
      'Challis': 'Custer',
      'Chubbuck': 'Bannock',
      'Clark Fork': 'Bonner',
      'Clayton': 'Custer',
      'Clifton': 'Franklin',
      "Coeur d'Alene": 'Kootenai',
      'Cottonwood': 'Idaho',
      'Council': 'Adams',
      'Craigmont': 'Lewis',
      'Crouch': 'Boise',
      'Culdesac': 'Nez Perce',
      'Dalton Gardens': 'Kootenai',
      'Dayton': 'Franklin',
      'Deary': 'Latah',
      'Declo': 'Cassia',
      'Dietrich': 'Lincoln',
      'Donnelly': 'Valley',
      'Dover': 'Bonner',
      'Downey': 'Bannock',
      'Driggs': 'Teton',
      'Drummond': 'Fremont',
      'Dubois': 'Clark',
      'Eagle': 'Ada',
      'East Hope': 'Bonner',
      'Eden': 'Jerome',
      'Elk River': 'Clearwater',
      'Emmett': 'Gem',
      'Fairfield': 'Camas',
      'Ferdinand': 'Idaho',
      'Fernan Lake Village': 'Kootenai',
      'Filer': 'Twin Falls',
      'Firth': 'Bingham',
      'Franklin': 'Franklin',
      'Fruitland': 'Payette',
      'Garden City': 'Ada',
      'Genesee': 'Latah',
      'Georgetown': 'Bear Lake',
      'Glenns Ferry': 'Elmore',
      'Gooding': 'Gooding',
      'Grace': 'Caribou',
      'Grand View': 'Owyhee',
      'Grangeville': 'Idaho',
      'Greenleaf': 'Canyon',
      'Hagerman': 'Gooding',
      'Hailey': 'Blaine',
      'Hansen': 'Twin Falls',
      'Harrison': 'Kootenai',
      'Hauser': 'Kootenai',
      'Hayden': 'Kootenai',
      'Hayden Lake': 'Kootenai',
      'Hazelton': 'Jerome',
      'Heyburn': 'Minidoka',
      'Hollister': 'Twin Falls',
      'Homedale': 'Owyhee',
      'Hope': 'Bonner',
      'Horseshoe Bend': 'Boise',
      'Huetter': 'Kootenai',
      'Idaho City': 'Boise',
      'Idaho Falls': 'Bonneville',
      'Inkom': 'Bannock',
      'Iona': 'Bonneville',
      'Irwin': 'Bonneville',
      'Island Park': 'Fremont',
      'Jerome': 'Jerome',
      'Juliaetta': 'Latah',
      'Kamiah': 'Lewis',
      'Kellogg': 'Shoshone',
      'Kendrick': 'Latah',
      'Ketchum': 'Blaine',
      'Kimberly': 'Twin Falls',
      'Kooskia': 'Idaho',
      'Kootenai': 'Bonner',
      'Kuna': 'Ada',
      'Lapwai': 'Nez Perce',
      'Lava Hot Springs': 'Bannock',
      'Leadore': 'Lemhi',
      'Lewiston': 'Nez Perce',
      'Lewisville': 'Jefferson',
      'Lost River': 'Butte',
      'Mackay': 'Custer',
      'Malad City': 'Oneida',
      'Malta': 'Cassia',
      'Marsing': 'Owyhee',
      'McCall': 'Valley',
      'McCammon': 'Bannock',
      'Melba': 'Canyon',
      'Menan': 'Jefferson',
      'Meridian': 'Ada',
      'Midvale': 'Washington',
      'Middleton': 'Canyon',
      'Minidoka': 'Minidoka',
      'Montpelier': 'Bear Lake',
      'Moore': 'Butte',
      'Moscow': 'Latah',
      'Mountain Home': 'Elmore',
      'Moyie Springs': 'Boundary',
      'Mud Lake': 'Jefferson',
      'Mullan': 'Shoshone',
      'Murtaugh': 'Twin Falls',
      'Nampa': 'Canyon',
      'Nezperce': 'Lewis',
      'New Meadows': 'Adams',
      'New Plymouth': 'Payette',
      'Newdale': 'Fremont',
      'Notus': 'Canyon',
      'Oakley': 'Cassia',
      'Oldtown': 'Bonner',
      'Onaway': 'Latah',
      'Orofino': 'Clearwater',
      'Osburn': 'Shoshone',
      'Oxford': 'Franklin',
      'Paris': 'Bear Lake',
      'Parma': 'Canyon',
      'Paul': 'Minidoka',
      'Payette': 'Payette',
      'Peck': 'Nez Perce',
      'Pierce': 'Clearwater',
      'Pinehurst': 'Shoshone',
      'Placerville': 'Boise',
      'Plummer': 'Benewah',
      'Pocatello': 'Bannock',
      'Ponderay': 'Bonner',
      'Post Falls': 'Kootenai',
      'Potlatch': 'Latah',
      'Preston': 'Franklin',
      'Priest River': 'Bonner',
      'Rathdrum': 'Kootenai',
      'Reubens': 'Lewis',
      'Rexburg': 'Madison',
      'Richfield': 'Lincoln',
      'Rigby': 'Jefferson',
      'Riggins': 'Idaho',
      'Ririe': 'Jefferson',
      'Roberts': 'Jefferson',
      'Rockland': 'Power',
      'Rupert': 'Minidoka',
      'St. Anthony': 'Fremont',
      'St. Charles': 'Bear Lake',
      'St. Maries': 'Benewah',
      'Salmon': 'Lemhi',
      'Sandpoint': 'Bonner',
      'Shelley': 'Bingham',
      'Shoshone': 'Lincoln',
      'Smelterville': 'Shoshone',
      'Soda Springs': 'Caribou',
      'Spirit Lake': 'Kootenai',
      'Spencer': 'Clark',
      'Stanley': 'Custer',
      'Star': 'Ada',
      'State Line': 'Kootenai',
      'Stites': 'Idaho',
      'Sugar City': 'Madison',
      'Sun Valley': 'Blaine',
      'Swan Valley': 'Bonneville',
      'Tensed': 'Benewah',
      'Tetonia': 'Teton',
      'Teton': 'Fremont',
      'Troy': 'Latah',
      'Twin Falls': 'Twin Falls',
      'Ucon': 'Bonneville',
      'Victor': 'Teton',
      'Wallace': 'Shoshone',
      'Warm River': 'Fremont',
      'Weippe': 'Clearwater',
      'Weiser': 'Washington',
      'Wendell': 'Gooding',
      'Weston': 'Franklin',
      'White Bird': 'Idaho',
      'Wilder': 'Canyon',
      'Winchester': 'Lewis',
      'Worley': 'Kootenai',
    },
  },

  WA: {
    label: 'Washington',
    cities: {
      'Aberdeen': 'Grays Harbor',
      'Airway Heights': 'Spokane',
      'Albion': 'Whitman',
      'Algona': 'King',
      'Almira': 'Lincoln',
      'Anacortes': 'Skagit',
      'Arlington': 'Snohomish',
      'Asotin': 'Asotin',
      'Auburn': 'King',
      'Bainbridge Island': 'Kitsap',
      'Battle Ground': 'Clark',
      'Beaux Arts Village': 'King',
      'Bellevue': 'King',
      'Bellingham': 'Whatcom',
      'Benton City': 'Benton',
      'Bingen': 'Klickitat',
      'Black Diamond': 'King',
      'Blaine': 'Whatcom',
      'Bonney Lake': 'Pierce',
      'Bothell': 'King',
      'Bremerton': 'Kitsap',
      'Brewster': 'Okanogan',
      'Bridgeport': 'Douglas',
      'Brier': 'Snohomish',
      'Buckley': 'Pierce',
      'Bucoda': 'Thurston',
      'Burien': 'King',
      'Burlington': 'Skagit',
      'Camas': 'Clark',
      'Carbonado': 'Pierce',
      'Carnation': 'King',
      'Cashmere': 'Chelan',
      'Castle Rock': 'Cowlitz',
      'Cathlamet': 'Wahkiakum',
      'Centralia': 'Lewis',
      'Chehalis': 'Lewis',
      'Chelan': 'Chelan',
      'Cheney': 'Spokane',
      'Chewelah': 'Stevens',
      'Clarkston': 'Asotin',
      'Cle Elum': 'Kittitas',
      'Clyde Hill': 'King',
      'Colfax': 'Whitman',
      'College Place': 'Walla Walla',
      'Colton': 'Whitman',
      'Colville': 'Stevens',
      'Conconully': 'Okanogan',
      'Concrete': 'Skagit',
      'Connell': 'Franklin',
      'Cosmopolis': 'Grays Harbor',
      'Coulee City': 'Grant',
      'Coulee Dam': 'Okanogan',
      'Coupeville': 'Island',
      'Covington': 'King',
      'Creston': 'Lincoln',
      'Cusick': 'Pend Oreille',
      'Darrington': 'Snohomish',
      'Davenport': 'Lincoln',
      'Dayton': 'Columbia',
      'Deer Park': 'Spokane',
      'Des Moines': 'King',
      'DuPont': 'Pierce',
      'Duvall': 'King',
      'East Wenatchee': 'Douglas',
      'Eatonville': 'Pierce',
      'Edgewood': 'Pierce',
      'Edmonds': 'Snohomish',
      'Electric City': 'Grant',
      'Ellensburg': 'Kittitas',
      'Elma': 'Grays Harbor',
      'Elmer City': 'Okanogan',
      'Endicott': 'Whitman',
      'Entiat': 'Chelan',
      'Enumclaw': 'King',
      'Ephrata': 'Grant',
      'Everett': 'Snohomish',
      'Everson': 'Whatcom',
      'Fairfield': 'Spokane',
      'Farmington': 'Whitman',
      'Federal Way': 'King',
      'Ferndale': 'Whatcom',
      'Fife': 'Pierce',
      'Fircrest': 'Pierce',
      'Forks': 'Clallam',
      'Friday Harbor': 'San Juan',
      'Garfield': 'Whitman',
      'George': 'Grant',
      'Gig Harbor': 'Pierce',
      'Gold Bar': 'Snohomish',
      'Goldendale': 'Klickitat',
      'Grand Coulee': 'Grant',
      'Grandview': 'Yakima',
      'Granger': 'Yakima',
      'Granite Falls': 'Snohomish',
      'Hamilton': 'Skagit',
      'Harrah': 'Yakima',
      'Harrington': 'Lincoln',
      'Hartline': 'Grant',
      'Hatton': 'Adams',
      'Hoquiam': 'Grays Harbor',
      'Hunts Point': 'King',
      'Ilwaco': 'Pacific',
      'Index': 'Snohomish',
      'Ione': 'Pend Oreille',
      'Issaquah': 'King',
      'Kahlotus': 'Franklin',
      'Kalama': 'Cowlitz',
      'Kelso': 'Cowlitz',
      'Kenmore': 'King',
      'Kennewick': 'Benton',
      'Kent': 'King',
      'Kettle Falls': 'Stevens',
      'Kirkland': 'King',
      'Kittitas': 'Kittitas',
      'Krupp': 'Grant',
      'La Center': 'Clark',
      'La Conner': 'Skagit',
      'LaCrosse': 'Whitman',
      'Lacey': 'Thurston',
      'Lake Forest Park': 'King',
      'Lake Stevens': 'Snohomish',
      'Lakewood': 'Pierce',
      'Lamont': 'Whitman',
      'Langley': 'Island',
      'Latah': 'Spokane',
      'Leavenworth': 'Chelan',
      'Liberty Lake': 'Spokane',
      'Lind': 'Adams',
      'Long Beach': 'Pacific',
      'Longview': 'Cowlitz',
      'Lyman': 'Skagit',
      'Lynden': 'Whatcom',
      'Lynnwood': 'Snohomish',
      'Mabton': 'Yakima',
      'Malden': 'Whitman',
      'Mansfield': 'Douglas',
      'Maple Valley': 'King',
      'Marcus': 'Stevens',
      'Marysville': 'Snohomish',
      'Mattawa': 'Grant',
      'McCleary': 'Grays Harbor',
      'Medical Lake': 'Spokane',
      'Medina': 'King',
      'Mercer Island': 'King',
      'Mesa': 'Franklin',
      'Metaline': 'Pend Oreille',
      'Metaline Falls': 'Pend Oreille',
      'Mill Creek': 'Snohomish',
      'Millwood': 'Spokane',
      'Milton': 'Pierce',
      'Monroe': 'Snohomish',
      'Montesano': 'Grays Harbor',
      'Morton': 'Lewis',
      'Moses Lake': 'Grant',
      'Mossyrock': 'Lewis',
      'Mount Vernon': 'Skagit',
      'Mountlake Terrace': 'Snohomish',
      'Moxee': 'Yakima',
      'Mukilteo': 'Snohomish',
      'Naches': 'Yakima',
      'Napavine': 'Lewis',
      'Nespelem': 'Okanogan',
      'Newcastle': 'King',
      'Newport': 'Pend Oreille',
      'Nooksack': 'Whatcom',
      'Normandy Park': 'King',
      'North Bend': 'King',
      'North Bonneville': 'Skamania',
      'Northport': 'Stevens',
      'Oak Harbor': 'Island',
      'Oakesdale': 'Whitman',
      'Oakville': 'Grays Harbor',
      'Ocean Shores': 'Grays Harbor',
      'Odessa': 'Lincoln',
      'Okanogan': 'Okanogan',
      'Olympia': 'Thurston',
      'Omak': 'Okanogan',
      'Oroville': 'Okanogan',
      'Orting': 'Pierce',
      'Othello': 'Adams',
      'Pacific': 'King',
      'Palouse': 'Whitman',
      'Pasco': 'Franklin',
      'Pateros': 'Okanogan',
      'Pe Ell': 'Lewis',
      'Pomeroy': 'Garfield',
      'Port Angeles': 'Clallam',
      'Port Orchard': 'Kitsap',
      'Port Townsend': 'Jefferson',
      'Poulsbo': 'Kitsap',
      'Prescott': 'Walla Walla',
      'Prosser': 'Benton',
      'Pullman': 'Whitman',
      'Puyallup': 'Pierce',
      'Quincy': 'Grant',
      'Rainier': 'Thurston',
      'Raymond': 'Pacific',
      'Reardan': 'Lincoln',
      'Redmond': 'King',
      'Renton': 'King',
      'Republic': 'Ferry',
      'Richland': 'Benton',
      'Ridgefield': 'Clark',
      'Ritzville': 'Adams',
      'Riverside': 'Okanogan',
      'Rock Island': 'Douglas',
      'Rockford': 'Spokane',
      'Rosalia': 'Whitman',
      'Roslyn': 'Kittitas',
      'Roy': 'Pierce',
      'Royal City': 'Grant',
      'Ruston': 'Pierce',
      'Sammamish': 'King',
      'SeaTac': 'King',
      'Seattle': 'King',
      'Sedro-Woolley': 'Skagit',
      'Selah': 'Yakima',
      'Sequim': 'Clallam',
      'Shelton': 'Mason',
      'Shoreline': 'King',
      'Skykomish': 'King',
      'Snohomish': 'Snohomish',
      'Snoqualmie': 'King',
      'Soap Lake': 'Grant',
      'South Bend': 'Pacific',
      'South Cle Elum': 'Kittitas',
      'South Prairie': 'Pierce',
      'Spangle': 'Spokane',
      'Spokane': 'Spokane',
      'Spokane Valley': 'Spokane',
      'Sprague': 'Lincoln',
      'Springdale': 'Stevens',
      'St. John': 'Whitman',
      'Stanwood': 'Snohomish',
      'Starbuck': 'Columbia',
      'Steilacoom': 'Pierce',
      'Stevenson': 'Skamania',
      'Sultan': 'Snohomish',
      'Sumas': 'Whatcom',
      'Sumner': 'Pierce',
      'Sunnyside': 'Yakima',
      'Tacoma': 'Pierce',
      'Tekoa': 'Whitman',
      'Tenino': 'Thurston',
      'Tieton': 'Yakima',
      'Toledo': 'Lewis',
      'Tonasket': 'Okanogan',
      'Toppenish': 'Yakima',
      'Tukwila': 'King',
      'Tumwater': 'Thurston',
      'Twisp': 'Okanogan',
      'Union Gap': 'Yakima',
      'Uniontown': 'Whitman',
      'University Place': 'Pierce',
      'Vader': 'Lewis',
      'Vancouver': 'Clark',
      'Waitsburg': 'Walla Walla',
      'Walla Walla': 'Walla Walla',
      'Wapato': 'Yakima',
      'Warden': 'Grant',
      'Washougal': 'Clark',
      'Washtucna': 'Adams',
      'Waterville': 'Douglas',
      'Waverly': 'Spokane',
      'Wenatchee': 'Chelan',
      'West Richland': 'Benton',
      'Westport': 'Grays Harbor',
      'White Salmon': 'Klickitat',
      'Wilbur': 'Lincoln',
      'Wilkeson': 'Pierce',
      'Wilson Creek': 'Grant',
      'Winlock': 'Lewis',
      'Winthrop': 'Okanogan',
      'Woodinville': 'King',
      'Woodland': 'Cowlitz',
      'Woodway': 'Snohomish',
      'Yacolt': 'Clark',
      'Yakima': 'Yakima',
      'Yarrow Point': 'King',
      'Yelm': 'Thurston',
      'Zillah': 'Yakima',
    },
  },
};

// Helpers shared by the staff form, the employer wizard and the review queue.
globalThis.LOCATION_HELPERS = {
  states() {
    return Object.keys(globalThis.LOCATION_DATA || {});
  },

  stateLabel(state) {
    return globalThis.LOCATION_DATA?.[state]?.label || state || '';
  },

  // Cities in a state, optionally narrowed to one county.
  citiesFor(state, county = '') {
    const cities = globalThis.LOCATION_DATA?.[state]?.cities;
    if (!cities) return [];
    const names = Object.keys(cities);
    const filtered = county ? names.filter((city) => cities[city] === county) : names;
    return filtered.sort((a, b) => a.localeCompare(b));
  },

  // Counties are derived from the city map so the two can never drift apart.
  countiesFor(state) {
    const cities = globalThis.LOCATION_DATA?.[state]?.cities;
    if (!cities) return [];
    return [...new Set(Object.values(cities))].sort((a, b) => a.localeCompare(b));
  },

  countyForCity(state, city) {
    return globalThis.LOCATION_DATA?.[state]?.cities?.[city] || '';
  },
};
